# permissions for end users to view objstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: objstore-viewer-role
rules:
- apiGroups:
  - cninf.danlabs.local
  resources:
  - objstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cninf.danlabs.local
  resources:
  - objstores/status
  verbs:
  - get
